[package]
name = "convert-queue"
version = "0.1.0"
edition = "2024"

[dependencies]
eink-convert = { version = "*", path = "../convert" }
env_logger = { version = "^0.11.11" }
image = { version = "^0.25.10" }
log = { version = "^0.4.34" }
serde = { version = "^1.0.229", features = ["derive"] }
serde_json = { version = "^1.0.151" }
tokio = { version = "^1.53.2", features = ["full"] }
zeromq = { version = "^0.6.0" }