[package]
name = "eink-display"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { version = "^0.1.41" }
tracing-subscriber = { version = "^0.3.20" }
embedded-hal = { version = "^1.0.0" }
linux-embedded-hal = { version = "^0.4.0"}


# hey joe, you can't use this because it doesn't support sending over two channels at once.
#rpi-pal = { version = "^0.22.2", features = ["embedded-hal"] }