[package]
name = "eink-convert"
version = "0.2.0"
edition = "2024"

[dependencies]
image = { version = "^0.25.8" }
imageproc = { version = "0.25.0" }
palette = { version = "^0.7.6"}
tracing = { version = "^0.1.41" }
